services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db-s
    environment:
      MYSQL_ROOT_PASSWORD: Lahari@2006
      MYSQL_DATABASE: examdb205
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: laharialapati/2300031852-exam-backend:latest
    container_name: springboot-s
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: laharialapati/2300031852-exam-frontend:latest
    container_name: react-s
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net: